language: python
addons:
- firefox: latest
python:
- 3.7.4
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- coverage run manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  app:ms-tdd-tutorial
  api_key:
    secure:IAX7JKy3B8peTl1l61gxac96XsJj6sH6ZUcSCgh6eIeuVv027msPXMFA+pk7HntjqEG0X1gKAUI5JtEWiYCHT+rHt8NNeuvI5WLiye0Y0i6DIeEOHaKZhFFnb07to+FhxDZdtoUgJTKA4L9N+ubbV+UE91VZsR8i8HSev62hV4JeKCrUR2KgdDbQz3Xs4iMY0wyXnonJSSKD8EMuPayWkKvNjW0co8Tg3uf+IKHUNoKmZvoSVFLcnGJikAv+CNkcJTP8dPOBF/c3dFK/0L9cIoknpfwkIgW6wQpv6SykZfKcaSH7r3hL1f3fcXPcMd9eVz3H/LGDKUVpw1FDU1s0xYa/jKwjHzrzLPfKKagmmTsx9JSV8wNSaiBkY2l4uWh+UNZJMe55zVLqQ7AKabCUguCMwlhJaDMO7g+YSbYT2Q4x6pXYYO29mXoAZXsGlUoXt40pKKI9bHhpYnUSLablDBs8icOPeQyx/cgEjEDMhVkJskBf6vidDDSM3IRByLHUdb69bn415SNtrZ99TyjLimN0iMk9DnBxsQZZWfX6USWSxk1lvW3lv2+RK7wLnYg/9S8f4GJHPqvCoi2apnlj2Dq1a/Jvj0GPLy82AB6P0tZX84VbDpLPu6l4sYqC1A7JyNQuJodwcH+IEzcQ3j0daSrYAzznrW3z0HqkRXNumUQ=
  on: MN_ICTRAINING-661_tdd