language: python
addons:
- firefox: latest
python:
- 3.7.4
before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- coverage run manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  app: ms-tdd-tutorial
  on: MS_ICTRAINING-697_TDD-Training
  api_key:
    secure: fgTPxLhs0WT4MqOwTO7NkQ8Rug5TCMY3KoHaA0ZGZvDrM/uX+0W5LXtfIDv4yHpFe0yNvDFzOZ1Vs8cg9hjKMrFcSb+jRhS7jj2LuCT3NE2gZn108SG6Yy9vexxS4H+hlPjxqVZuBidKeEVAWbv3LjuCDJamq/sVhvIrMSM6cF1sa/1tAbqWYbDFFVTNXb58qBXEG9UpW4dnMAdzgEfKvNwaEGqV4mu8Jk8yR+q1nbOXpZNncoQHPEERvx38kNLqfREV31Rcl0K5ICk03DOUHawi4EOmYk6mfGUXjW71sp9EdT3xXJaF2iRdUUnRPJdkXdHsMMXEKgePuvVKujRx/og3tmUd5i0sqbGyJnSntwhIA98iK0Fp/7fHiRgnn2VwBKdL4ZLvzyfDp+mLA51JzVpT1Ext+iUUO6ALmwv8/4oXplmgUtswAUp7CkzoY0uPqMiiSC9/+RmjF0HCSLt3qkUrRCrbdnTK46nOpFXIzamdzJMdu8g1yXkVnnKiSfabB7vbDLSwt3Kk5+ZsfmqNqorgO6crk4MOwTIttCGGBfCCCljZ+9pxEwwY/NXLZm2IoFP86JHx1ULNzX5H1O05eh80T7Axbn6GhF2OaL687ZztTOABqj0bPHfCH9U27WdA5Z8GH7QlL1T+trUJmuz3UyvDacTPOE7afGLDTrizzzk=
